server:
  port: 8080

ribbon.eureka.enabled: false     #是否从注册中心获取

config.db:
  host: 192.168.1.20
  port: 3306
  name: gateway
  user: root
  pass: 123456

spring:
  # datasource
  datasource:
    url: jdbc:mysql://${config.db.host}:${config.db.port}/${config.db.name}?characterEncoding=utf8&useSSL=true
    username: ${config.db.user}
    password: ${config.db.pass}
    driverClassName: com.mysql.jdbc.Driver

    http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 50Mb

  # Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect